02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Admin/Controllers/CourseInstancesController.cs
using Microsoft.AspNetCore.Mvc;
using SoftUniClone.Common.Admin.BindingModels;
using SoftUniClone.Services.Admin.Interfaces;
using System;
using System.Threading.Tasks;

namespace SoftUniClone.Web.Areas.Admin.Controllers
{
    public class CourseInstancesController : AdminController
    {
        private readonly IAdminCourseInstancesService courseInstancesService;

        public CourseInstancesController(IAdminCourseInstancesService courseInstancesService)
        {
            this.courseInstancesService = courseInstancesService;
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
            var model = await this.courseInstancesService.PrepareInstanceForCreationAsync(courseId: id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(InstanceCreationBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            int instanceId = await this.courseInstancesService.CreateInstanceAsync(model);
            // TODO: redirect to details
            return RedirectToAction("Details", new { id = instanceId });
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            // TODO: Implement this
            throw new NotImplementedException();
        }
    }
}

02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Admin/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using SoftUniClone.Common.Admin.BindingModels;
using SoftUniClone.Services.Admin.Interfaces;
using SoftUniClone.Web.Helpers.Messages;
using System.Threading.Tasks;

namespace SoftUniClone.Web.Areas.Admin.Controllers
{
    public class CoursesController : AdminController
    {
        private readonly IAdminCoursesService coursesService;

        public CoursesController(
            IAdminCoursesService coursesService)
        {
            this.coursesService = coursesService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var courses = await this.coursesService.GetCoursesAsync();
            return View(courses);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourseCreationBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            await this.coursesService.AddCourseAsync(model);

            this.TempData["__Message"] = new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Course created successfully."
            };

            return RedirectToAction("Details");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var model = await this.coursesService.GetCourseDetailsAsync(id);
            return View(model);
        }
    }
}

02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Admin/Controllers/UsersController.cs
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SoftUniClone.Common.Admin.ViewModels;
using SoftUniClone.Data;
using SoftUniClone.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftUniClone.Web.Areas.Admin.Controllers
{
    public class UsersController : AdminController
    {
        private readonly SoftUniCloneContext context;
        private readonly IMapper mapper;
        private readonly UserManager<User> userManager;

        public UsersController(
            SoftUniCloneContext context,
            IMapper mapper,
            UserManager<User> userManager)
        {
            this.context = context;
            this.mapper = mapper;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await this.userManager.GetUserAsync(this.User);
            var users = this.context.Users
                .Where(u => u.Id != currentUser.Id)
                .ToList();

            // TODO: Fill in "Is lecturer" -> whether user is in role "Lecturer"?
            // TODO: Is admin
            // If lecturer -> hide button "Make lecturer"
            // If administrator -> only "Details"
            var model = this.mapper.Map<IEnumerable<UserConciseViewModel>>(users);
            return View(model);
        }

        public async Task<IActionResult> Details(string id)
        {
            // TODO: If administrator -> disable editing
            var currentUser = await this.userManager.GetUserAsync(this.User);
            if (id == currentUser.Id)
            {
                return Unauthorized();
            }

            var user = await this.context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var roles = await this.userManager.GetRolesAsync(user);
            var model = this.mapper.Map<UserDetailsViewModel>(user);
            model.Roles = roles;
            return View(model);
        }
    }
}

02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Lecturer/Controllers/CourseInstancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SoftUniClone.Services.Lecturer.Interfaces;

namespace SoftUniClone.Web.Areas.Lecturer.Controllers
{
    public class CourseInstancesController : LecturerController
    {
        private readonly ILecturerCourseInstancesService courseInstancesService;

        public CourseInstancesController(
            ILecturerCourseInstancesService courseInstancesService)
        {
            this.courseInstancesService = courseInstancesService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View();
        }

        //[HttpPost]
        //public async Task<IActionResult> Edit(int id, CourseInstanceEditingModel model)
        //{
        //    await this.courseInstancesService.Edit(id, this.User);
        //    return View();
        //}
    }
}

02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Admin/Views/Shared/DisplayTemplates/CourseConciseViewModel.cshtml
@model CourseConciseViewModel

<li>
    <a asp-area="Admin" asp-controller="Courses" asp-action="Details" asp-route-id="@Model.Id">@Model.Name</a>
</li>

02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Admin/Views/Shared/DisplayTemplates/CourseInstanceViewModel.cshtml
@model CourseInstanceViewModel
<li>
    @Model.Name
</li>

02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Admin/Views/Shared/DisplayTemplates/UserConciseViewModel.cshtml
@model UserConciseViewModel

<tr>
    <td>@Model.Username</td>
    <td>@Model.Email</td>
    <td>@Html.DisplayFor(model => model.IsLecturer)</td>
    <td>@Html.DisplayFor(model => model.IsAdmin)</td>
    <td>
        <a asp-area="Admin" asp-controller="Users" asp-action="Details" asp-route-id="@Model.Id"
           class="btn btn-default">Details</a>
        <a asp-area="Admin" asp-controller="Users" asp-action="MakeLecturer" asp-route-id="@Model.Id"
           class="btn btn-primary">
            Make lecturer
        </a>
        <a asp-area="Admin" asp-controller="Users" asp-action="ChangePassword" asp-route-id="@Model.Id"
           class="btn btn-warning">
            Change password
        </a>
        <a asp-area="Admin" asp-controller="Users" asp-action="Ban" asp-route-id="@Model.Id"
           class="btn btn-danger">
            Ban
        </a>
    </td>
</tr>

02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Admin/Views/Shared/DisplayTemplates/UserDetailsViewModel.cshtml
@model UserDetailsViewModel
<p><strong>Username:</strong> @Model.Username</p>
<p><strong>Email:</strong> <a href="mailto://@Model.Email">@Model.Email</a></p>
<p><strong>Full name:</strong> @Model.FullName</p>
<p>
    <strong>Roles:</strong>
    <ul>
        <li>Student</li>
        @if (Model.Roles.Any())
        {
            @foreach (string role in Model.Roles)
            {
                <li>@role</li>
            }
        }
    </ul>
</p>