02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Admin/Controllers/CourseInstancesController.cs
using Microsoft.AspNetCore.Mvc;
using SoftUniClone.Common.Admin.BindingModels;
using SoftUniClone.Services.Admin.Interfaces;
using System;
using System.Threading.Tasks;

namespace SoftUniClone.Web.Areas.Admin.Controllers
{
    public class CourseInstancesController : AdminController
    {
        private readonly IAdminCourseInstancesService courseInstancesService;

        public CourseInstancesController(IAdminCourseInstancesService courseInstancesService)
        {
            this.courseInstancesService = courseInstancesService;
        }

        [HttpGet]
        public async Task<IActionResult> Create(int id)
        {
            var model = await this.courseInstancesService.PrepareInstanceForCreationAsync(courseId: id);
            if (model == null)
            {
                return NotFound();
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(InstanceCreationBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            int instanceId = await this.courseInstancesService.CreateInstanceAsync(model);
            // TODO: redirect to details
            return RedirectToAction("Details", new { id = instanceId });
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            // TODO: Implement this
            throw new NotImplementedException();
        }
    }
}

02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Admin/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using SoftUniClone.Common.Admin.BindingModels;
using SoftUniClone.Services.Admin.Interfaces;
using SoftUniClone.Web.Helpers.Messages;
using System.Threading.Tasks;

namespace SoftUniClone.Web.Areas.Admin.Controllers
{
    public class CoursesController : AdminController
    {
        private readonly IAdminCoursesService coursesService;

        public CoursesController(
            IAdminCoursesService coursesService)
        {
            this.coursesService = coursesService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var courses = await this.coursesService.GetCoursesAsync();
            return View(courses);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CourseCreationBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            await this.coursesService.AddCourseAsync(model);

            this.TempData["__Message"] = new MessageModel()
            {
                Type = MessageType.Success,
                Message = "Course created successfully."
            };

            return RedirectToAction("Details");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var model = await this.coursesService.GetCourseDetailsAsync(id);
            return View(model);
        }
    }
}

02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Lecturer/Controllers/CourseInstancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SoftUniClone.Services.Lecturer.Interfaces;

namespace SoftUniClone.Web.Areas.Lecturer.Controllers
{
    public class CourseInstancesController : LecturerController
    {
        private readonly ILecturerCourseInstancesService courseInstancesService;

        public CourseInstancesController(
            ILecturerCourseInstancesService courseInstancesService)
        {
            this.courseInstancesService = courseInstancesService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View();
        }

        //[HttpPost]
        //public async Task<IActionResult> Edit(int id, CourseInstanceEditingModel model)
        //{
        //    await this.courseInstancesService.Edit(id, this.User);
        //    return View();
        //}
    }
}

02.CS_WebDev/Web_-_May_2018/MVC_ASP.NET_Core_-_Jun_2018/08. Architecture-Part-II/ArchitectureIIExercises/SoftUniClone.Web/Areas/Admin/Views/CourseInstances/Create.cshtml
@model InstanceCreationBindingModel
@{
    ViewData["Title"] = "Create instance";
}

<h2>Create instance for course @Model.Name</h2>
<form asp-area="Admin" asp-controller="CourseInstances" asp-action="Create" method="post">
    <input type="hidden" asp-for="CourseId" />
    @Html.FormGroupFor(model => model.Name)
    @Html.FormGroupFor(model => model.Slug)
    @Html.FormGroupFor(model => model.Description)
    @Html.FormGroupFor(model => model.LecturerId)
    @Html.FormGroupFor(model => model.StartDate)
    @Html.FormGroupFor(model => model.EndDate)
    <div class="form-group">
        <div class="col-sm-10 col-sm-push-2">
            <input type="submit" value="Create" class="btn btn-success" />
            <a asp-area="Admin" asp-controller="Courses" asp-action="Index" class="btn btn-default">Cancel</a>
        </div>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/create-slug.js"></script>
    <script>
        $(function () {
            createSlug("@(Html.IdFor(model => model.Name))", "@(Html.IdFor(model => model.Slug))");
         });
    </script>
}